### ISSUE TITLE
Error running example workflow for Ebola outbreak

### ISSUE THREAD

**Issue by sean-la** [NCBI-Hackathons/Virus_Detection_SRA#8]
I'm testing my installation of sidearm on my machine. I've installed all the dependencies and I'm trying the first example workflow on the Ebola virus outbreak. When I run the command `./sidearm.cwl sidearm.SRR1553459.ebola.yml`, I get the error:

```
[las2@lmem06 tools]$ ./sidearm.cwl sidearm.SRR1553459.ebola.yml 
/usr/bin/env: cwl-runner --preserve-environment BLASTDB --preserve-environment PERL5LIB: Permission denied
```

My cwl-runner installation works, too. I would really appreciate any help in fixing this error!

**Comment by neksa** [comment]
Could you run it with --debug ?

Could you also provide output
ls -l `which cwl-runner`

**Comment by neksa** [comment]
@pcantalupo   it is related to how  /usr/bin/env  works on Linux. It does not like --preserve-environment. I believe we change it and set environment in the yml file, or in cwl file, something along these lines:

https://github.com/common-workflow-language/common-workflow-language/blob/e831c206023e611e462146580fc8a0f07186167f/v1.0/v1.0/env-tool2.cwl

**Comment by pcantalupo** [comment]
@thefantasticdron Some things to try/think about:

"permission denied" leads me to believe that, for some reason, the file (cwl-runner) couldn't be executed. Please provide the output for this command:
```
ls -l `which cwl-runner`
```
What os are you using? @neksa seems to think it is related to Linux `env`

Could the partition that sidearm.cwl lives on be mounted in such a way as to not allow exec (see https://askubuntu.com/questions/295293/usr-bin-env-bash-permission-denied)

Finally, what happens when you try bypassing `env` using this command?
```
cwl-runner --preserve-environment PERL5LIB --preserve-environment BLASTDB sidearm.cwl sidearm.SRR1553459.ebola.yml
```

**Comment by neksa** [comment]
Paul, this is exactly what we did - bypassing the env, and it worked.
It was in fact /usr/bin/env that was printing "permission denied".
However, we had to remove --preserve-environment  from shebang lines in all CWL tools. I am not sure if environment variables are propagated down to individual tools in the workflow. Do you know?

@thefantasticdron has a different problem with BLASTDB env now and we are discussing it off the list because it may be related to specific Linux environment we have at NCBI. But it may also be a general issue related to --preserve-environement. If so, we'll post updates

**Comment by pcantalupo** [comment]
@neksa I don't know if env vars are propagated down to individual tools.
Thank you for your help!

**Comment by sean-la** [comment]
Bypassing `env` and using a Python virtual environment to install all the Python packages resolved this issue. Thanks!

**Comment by pcantalupo** [comment]
@thefantasticdron I've not used Python virtual environments before. For my understanding and others who may have this same issue, please describe any code changes you made and what do you mean by "all the Python packages"? Thanks!

**Comment by sean-la** [comment]
I created a python virtual environment using the commands `mkdir sidearm; virtualenv sidearm`.
I uninstalled the pip package `xopen` with the command `pip uninstall xopen`. 
I activated the python virtual environment using `source sidearm/bin/activate`, and then installed `xopen`, `cutadapt`, and `cwlref-runner` using `pip install`.
With all other dependencies installed, this allowed SIDEARM to work on my machine. No other code was changed.
